---
title: "R Notebook"
output: html_notebook
---


```{r}

pacman::p_load("tidyverse","lme4")

library(multilevelmod)

sleepstudy <- lme4::sleepstudy %>% group_by(Subject) %>% 
              # create a new random category just for plotting
              mutate(cat = sample( LETTERS[1:3], 1, replace=TRUE, prob=c(0.25, 0.50, 0.25))) %>%
              ungroup()

head(sleepstudy,30)


```




```{r}

# set engine to lme4
mixed_model_spec <- linear_reg() %>% set_engine("lmer")

# create model
mixed_model_fit_tidy <- 
  mixed_model_spec %>% 
  fit(Reaction ~ Days + cat + (1 | Subject), data = sleepstudy)

mixed_model_fit_tidy

```



```{r}

expanded_df_tidy <- with(sleepstudy,
                    data.frame(
                      expand.grid(Subject=levels(Subject),
                                  cat = unique(cat),
                                  Days=seq(min(Days),max(Days),length=51))))

```



```{r}

# the issue is that multilevelmod internally sets the default for prediction to re.form = NA; the code above resets it to re.form = NULL (which is the lme4 default, i.e. include all random effects in the prediction)

predicted_df_tidy <- mutate(expanded_df_tidy,
                            pred_rand = predict(mixed_model_fit_tidy,
                                                new_data=expanded_df_tidy, 
                                                type = "raw", opts=list(re.form=NULL)),
                            pred_fixed = predict(mixed_model_fit_tidy,
                                                new_data=expanded_df_tidy, 
                                                type = "raw", opts=list(re.form=NA)))


predict(mixed_model_fit_tidy,new_data=expanded_df_tidy,type = "raw", opts=list(re.form=NA))


ggplot(predicted_df_tidy,aes(x=Days,y=pred_rand,colour=Subject))+
       facet_wrap(.~cat) + 
       geom_line()


```

















