---
title: "R Notebook"
output: html_notebook
---


```{r}

pacman::p_load("tidyverse","lme4")

library(multilevelmod)

sleepstudy <- lme4::sleepstudy

```


```{r}

# install.packages("Rtools")
# 
# devtools::install_github("tidymodels/multilevelmod", force =T)

```



```{r}
# https://github.com/tidymodels/multilevelmod

#> Loading required package: parsnip
data(sleepstudy, package = "lme4")


# set engine to lme4
mixed_model_spec <- linear_reg() %>% set_engine("lmer")


# create model
mixed_model_fit_tidy <- 
  mixed_model_spec %>% 
  fit(Reaction ~ Days + (1 | Subject), data = sleepstudy)


mixed_model_fit_tidy


```



```{r}

expanded_df_tidy <- with(sleepstudy,
                    data.frame(
                      expand.grid(Subject=levels(Subject),
                                  Days=seq(min(Days),max(Days),length=51))))

```



```{r}

# the issue is that multilevelmod internally sets the default for prediction to re.form = NA; the code above resets it to re.form = NULL (which is the lme4 default, i.e. include all random effects in the prediction)

predicted_df_tidy <- mutate(expanded_df_tidy,
       .pred = predict(mixed_model_fit_tidy,
                       new_data=expanded_df_tidy, 
                       type = "raw", opts=list(re.form=NULL)))


predicted_df_tidy


ggplot(predicted_df_tidy,aes(x=Days,y=.pred,colour=Subject))+
       geom_line()


```

















