---
title: "R Notebook"
output: html_notebook
---


```{r}


# devtools::install_github("tidymodels/multilevelmod", force =T)
library("multilevelmod")
library("tidymodels")
library("tidyverse")
library("lme4")

sleepstudy <- lme4::sleepstudy

```


```{r}

# install.packages("Rtools")
# 
# devtools::install_github("tidymodels/multilevelmod", force =T)

```



```{r }
# https://github.com/tidymodels/multilevelmod

#> Loading required package: parsnip
data(sleepstudy, package = "lme4")


# set engine to lme4
mixed_model_spec <- linear_reg() %>% set_engine("lmer")


# create model
mixed_model_fit_tidy <- 
  mixed_model_spec %>% 
  fit(Reaction ~ Days + (1 | Subject), data = sleepstudy)


expanded_df_tidy <- with(sleepstudy,
                    data.frame(
                      expand.grid(Subject=levels(Subject),
                                  Days=seq(min(Days),max(Days),length=51))))


str(mixed_model_fit_tidy)

predicted_df_tidy <- data.frame(expanded_df_tidy,resp=predict(mixed_model_fit_tidy,new_data=expanded_df_tidy))


ggplot(predicted_df_tidy,aes(x=Days,y=.pred,colour=Subject))+
       geom_line()

```





```{r lme4 way}

mod <- lmer(Reaction ~ Days + (1|Subject),data=sleepstudy)

expanded_df <- with(sleepstudy,
                    data.frame(
                      expand.grid(Subject=levels(Subject),
                                  Days=seq(min(Days),max(Days),length=51))))

predicted_df <- data.frame(expanded_df,resp=predict(mod,newdata=expanded_df))

ggplot(predicted_df,aes(x=Days,y=resp,colour=Subject))+
       geom_line()

```


















